import Head from 'next/head'
import Layout from '../components/layout/Layout'
import styles from '../styles/Home.module.css'
import { lightTheme, darkTheme, GlobalStyles, StyledApp } from "../Theme.js";
import {UseGlobalContext} from '../components/Context';
import { ThemeProvider } from "styled-components";

export default function Home() {

  const {useDarkMode}=UseGlobalContext();
  const [ theme, toggleTheme ] = useDarkMode();
  

  return (
   <ThemeProvider theme={theme == "light" ? lightTheme : darkTheme}> 
        <GlobalStyles />
        <StyledApp> 
          <div>
            <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
          <Layout  theme={theme} toggleTheme={toggleTheme} >
              <p>Hello guys hello</p>
          </Layout>
        
          </div>
        </StyledApp>
    </ThemeProvider>
  )
}
